function plot_surface( A )
  % This plots the surface generated by taking matrix A
  % as a quadratic form.  A is assumed 2x2
  
  [x, y] = meshgrid(-5:1:5, -5:1:5);
  s = size(x);
  
  f = zeros(s);  % Preallocate f to be same size as x
  for i=1:s(1)
      for j=1:s(2)
          u = [x(i, j); y(i, j)];
          f(i,j) = u'*A*u;
      end
  end

  contour(x, y, f)        
  
end

